# Generated by Django 2.0.6 on 2018-06-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterOrganisation',
            fields=[
                ('orgId', models.AutoField(primary_key=True, serialize=False)),
                ('orgName', models.CharField(blank=True, max_length=255)),
                ('orgAdress', models.CharField(blank=True, max_length=255)),
                ('orgPhone', models.CharField(blank=True, max_length=255)),
                ('orgEmail', models.EmailField(blank=True, max_length=255)),
                ('orgCode', models.CharField(blank=True, max_length=255, unique=True)),
                ('orgPassword', models.CharField(blank=True, max_length=255)),
                ('is_active', models.IntegerField(default=1)),
            ],
        ),
    ]
