# Generated by Django 2.0.6 on 2018-07-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0003_auto_20180629_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('orgCode', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('is_active', models.IntegerField(default=1)),
            ],
        ),
    ]
