# Generated by Django 2.0.6 on 2018-07-02 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('orgCode', models.CharField(blank=True, max_length=255)),
                ('subCategory', models.CharField(blank=True, max_length=255)),
                ('is_active', models.IntegerField(default=1)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demo.Category')),
            ],
        ),
    ]
