# Generated by Django 2.0.6 on 2018-07-04 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0005_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookId', models.AutoField(primary_key=True, serialize=False)),
                ('orgCode', models.CharField(blank=True, max_length=255)),
                ('subCategory', models.CharField(blank=True, max_length=255)),
                ('bookName', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=255)),
                ('is_cd', models.CharField(blank=True, max_length=255)),
                ('copies', models.IntegerField(default=1)),
                ('is_active', models.IntegerField(default=1)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demo.Category')),
                ('subCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demo.SubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('bookCopyId', models.AutoField(primary_key=True, serialize=False)),
                ('bookCopyCode', models.CharField(blank=True, max_length=255)),
                ('is_active', models.IntegerField(default=1)),
                ('bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demo.Book')),
            ],
        ),
    ]
