# Generated by Django 2.0.6 on 2018-07-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0007_book_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='subCategory',
        ),
    ]
