# Generated by Django 2.0.6 on 2018-07-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0008_remove_book_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='is_reserved',
            field=models.IntegerField(default=0),
        ),
    ]
