# Generated by Django 2.0.6 on 2018-07-17 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0010_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='dateReserved',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
